/**
 * AI Commentary Panel (PR 5.0)
 *
 * CRITICAL INVARIANT: AI is commentary, not control.
 *
 * This panel displays read-only AI commentary. It has NO authority
 * and CANNOT affect system behavior.
 *
 * KILL CRITERIA (any violation fails PR 5.0):
 * - Panel is visible by default
 * - Panel contains interactive elements (buttons, links that act)
 * - Panel output influences system behavior
 * - Panel persists any data as authority
 * - Panel feeds back into validation or resolution
 *
 * The panel MUST be:
 * - Hidden by default
 * - Explicitly user-opened
 * - Clearly labeled "Advisory / Non-Authoritative"
 * - Visually subordinate to validation results and GM override controls
 * - Completely non-interactive (read-only text display)
 */

import type { PipelineResult, ValidationReport, GmOverride, ResolutionResult } from '../types';

// ============================================================================
// PANEL STATE (UI-ONLY, NON-AUTHORITATIVE)
// ============================================================================

/**
 * AICommentaryPanelState - state of the AI commentary panel
 *
 * This state is UI-ONLY. It has no authority and is not persisted.
 * The panel being open or closed does not affect system behavior.
 */
export type AICommentaryPanelState = {
  /** Is the panel visible? (Default: false - HIDDEN by default) */
  readonly isVisible: boolean;

  /** Is commentary currently loading? */
  readonly isLoading: boolean;

  /** The commentary text (markdown, read-only) */
  readonly commentary: string | null;

  /** Error message if commentary failed to load */
  readonly error: string | null;

  /** Timestamp when commentary was last fetched */
  readonly lastFetchedAt: number | null;
};

/**
 * Initial state - panel is HIDDEN by default
 *
 * CRITICAL: The default state MUST be hidden.
 * AI commentary is opt-in only.
 */
export const INITIAL_AI_COMMENTARY_STATE: AICommentaryPanelState = {
  isVisible: false,
  isLoading: false,
  commentary: null,
  error: null,
  lastFetchedAt: null,
};

// ============================================================================
// STATE TRANSITIONS (PURE FUNCTIONS, NO SIDE EFFECTS)
// ============================================================================

/**
 * Open the AI commentary panel
 *
 * CRITICAL: This is an EXPLICIT user action.
 * The panel is NEVER opened automatically.
 */
export function openPanel(state: AICommentaryPanelState): AICommentaryPanelState {
  return {
    ...state,
    isVisible: true,
  };
}

/**
 * Close the AI commentary panel
 */
export function closePanel(state: AICommentaryPanelState): AICommentaryPanelState {
  return {
    ...state,
    isVisible: false,
  };
}

/**
 * Toggle the AI commentary panel visibility
 */
export function togglePanel(state: AICommentaryPanelState): AICommentaryPanelState {
  return {
    ...state,
    isVisible: !state.isVisible,
  };
}

/**
 * Set loading state (when fetching commentary)
 */
export function setLoading(state: AICommentaryPanelState): AICommentaryPanelState {
  return {
    ...state,
    isLoading: true,
    error: null,
  };
}

/**
 * Set commentary (after successful fetch)
 *
 * @param state - Current state
 * @param commentary - The commentary text (markdown)
 */
export function setCommentary(
  state: AICommentaryPanelState,
  commentary: string
): AICommentaryPanelState {
  return {
    ...state,
    isLoading: false,
    commentary,
    error: null,
    lastFetchedAt: Date.now(),
  };
}

/**
 * Set error (after failed fetch)
 *
 * @param state - Current state
 * @param error - The error message
 */
export function setError(
  state: AICommentaryPanelState,
  error: string
): AICommentaryPanelState {
  return {
    ...state,
    isLoading: false,
    commentary: null,
    error,
    lastFetchedAt: Date.now(),
  };
}

/**
 * Clear commentary (reset to initial state, but keep visibility)
 */
export function clearCommentary(state: AICommentaryPanelState): AICommentaryPanelState {
  return {
    ...state,
    isLoading: false,
    commentary: null,
    error: null,
    lastFetchedAt: null,
  };
}

// ============================================================================
// RENDER HELPERS (PURE FUNCTIONS, TEXT OUTPUT ONLY)
// ============================================================================

/**
 * Panel header text - clearly labeled as advisory
 */
export const PANEL_HEADER = 'AI Commentary (Advisory Only)';

/**
 * Panel disclaimer - emphasizes non-authority
 */
export const PANEL_DISCLAIMER =
  'This commentary is generated by AI and has NO authority over game state. ' +
  'It is purely informational and advisory. The GM and rules engine are the sole authorities.';

/**
 * Render the panel to HTML string (for display)
 *
 * CRITICAL: This is READ-ONLY HTML.
 * - No interactive elements (no buttons, forms, links that act)
 * - No event handlers that modify state
 * - Pure text display only
 *
 * @param state - Current panel state
 * @returns HTML string for display (read-only)
 */
export function renderPanelHTML(state: AICommentaryPanelState): string {
  if (!state.isVisible) {
    return ''; // Hidden panel renders nothing
  }

  const lines: string[] = [];

  // Panel container with advisory styling
  lines.push('<aside class="ai-commentary-panel" aria-label="AI Commentary (Advisory)"');
  lines.push('  role="complementary"');
  lines.push('  data-authority="none"');
  lines.push('  style="opacity: 0.8; border-left: 3px solid #888; padding-left: 1em;">');

  // Header with clear advisory label
  lines.push(`  <header style="font-size: 0.9em; color: #666;">`);
  lines.push(`    <strong>${escapeHTML(PANEL_HEADER)}</strong>`);
  lines.push('  </header>');

  // Disclaimer
  lines.push('  <p style="font-size: 0.8em; color: #888; font-style: italic;">');
  lines.push(`    ${escapeHTML(PANEL_DISCLAIMER)}`);
  lines.push('  </p>');

  // Content area
  lines.push('  <div class="ai-commentary-content">');

  if (state.isLoading) {
    lines.push('    <p style="color: #666;">Loading commentary...</p>');
  } else if (state.error) {
    lines.push(`    <p style="color: #c00;">Commentary unavailable: ${escapeHTML(state.error)}</p>`);
    lines.push('    <p style="font-size: 0.8em; color: #888;">System behavior is unchanged.</p>');
  } else if (state.commentary) {
    // Render commentary as pre-formatted text (markdown display would be here)
    lines.push(`    <div class="ai-commentary-text" style="white-space: pre-wrap;">`);
    lines.push(`      ${escapeHTML(state.commentary)}`);
    lines.push('    </div>');
  } else {
    lines.push('    <p style="color: #888;">No commentary requested.</p>');
  }

  lines.push('  </div>');

  // Footer with timestamp
  if (state.lastFetchedAt) {
    const timestamp = new Date(state.lastFetchedAt).toLocaleTimeString();
    lines.push(`  <footer style="font-size: 0.7em; color: #aaa; margin-top: 1em;">`);
    lines.push(`    Generated at: ${escapeHTML(timestamp)} (advisory snapshot)`);
    lines.push('  </footer>');
  }

  lines.push('</aside>');

  return lines.join('\n');
}

/**
 * Escape HTML to prevent XSS
 *
 * CRITICAL: All user-visible text must be escaped.
 */
function escapeHTML(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// ============================================================================
// VALIDATION (ENSURES PANEL STAYS READ-ONLY)
// ============================================================================

/**
 * Validate that panel state has no authority indicators
 *
 * This function can be used by tests to verify the panel
 * has not accidentally gained authority.
 */
export function validateNoAuthority(state: AICommentaryPanelState): boolean {
  // Panel state should have no fields that could indicate authority
  const stateKeys = Object.keys(state);
  const forbiddenKeys = [
    'effectsToApply',
    'overrideRequest',
    'validationOverride',
    'intentModification',
    'pendingAction',
    'actionQueue',
  ];

  for (const key of stateKeys) {
    if (forbiddenKeys.includes(key)) {
      return false;
    }
  }

  return true;
}

// ============================================================================
// TYPE EXPORTS
// ============================================================================

export type { AICommentaryPanelState };
