/**
 * CharacterSheet Type (Phase 2.5a)
 *
 * Non-authoritative reference object for assistant context.
 * This is NOT game state - it's a text reference that gets
 * injected into natural language input.
 *
 * CRITICAL: These are descriptive aids, not canonical data.
 * The GM/user is always authoritative over actual game state.
 */

export type CharacterSheet = {
  readonly id: string;
  readonly name: string;
  readonly role: 'PC' | 'NPC';
  readonly description: string;
  readonly skills?: readonly string[];
  readonly equipment?: readonly string[];
  readonly notes?: string;
};

/**
 * Type for creating a new character sheet (id generated by backend)
 */
export type CharacterSheetCreate = Omit<CharacterSheet, 'id'>;

/**
 * Type for updating an existing character sheet
 */
export type CharacterSheetUpdate = Partial<CharacterSheetCreate>;
